name: Engine CI V2

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

env:
  # Please ensure that this is in sync with graalVersion in build.sbt
  graalVersion: 21.1.0
  # Please ensure that this is in sync with javaVersion in build.sbt
  javaVersion: 11
  # Please ensure that this is in sync with project/build.properties
  sbtVersion: 1.5.2
  # Please ensure that this is in sync with rustVersion in build.sbt
  rustToolchain: nightly-2021-11-29
  # Some moderately recent version of Node.JS is needed to run the library download tests.
  nodeVersion: 14.17.2

jobs:
  test_and_publish_win:
    name: Engine
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
      - engine
    timeout-minutes: 120
    strategy:
      matrix:
        os: [Windows, Linux]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: cargo run --release --bin build-enso -- ${{ github.workspace }}

      #####################
      # PUBLISH ARTIFACTS #
      #####################
      - name: Publish the Engine Distribution Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENGINE_DIST_NAME }}
          path: ${{ env.ENGINE_DIST_ROOT }}/${{ env.ENGINE_DIST_NAME }}.zip
      - name: Publish the Launcher
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.LAUNCHER_DIST_NAME }}
          path: ${{ env.LAUNCHER_DIST_ROOT }}
      - name: Publish the Project Manager
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECTMANAGER_DIST_NAME }}
          path: ${{ env.PROJECTMANAGER_DIST_ROOT }}
      - name: Publish the FlatBuffers Schemas
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: Engine Protocol FlatBuffers Schemas
          path: ${{ env.TARGET_DIR }}/fbs-upload/fbs-schema.zip
      - name: Publish the Parser JS Bundle
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: Parser JS Bundle
          path: ${{ env.TARGET_DIR }}/scala-parser.js
      - name: Publish the Manifest
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: manifest
          path: ${{ env.ENGINE_DIST_DIR }}/manifest.yaml
